#!/bin/bash
#createhtml2: create html for accessing via web browser.
#$1: url to get from.
root=$(dirname $0)/../master
cd $root
find . -name index.html|xargs rm -rf -
find . -type d |while read dir
do
  if [ ${#dir} -lt 2 ];then
    url=${1}
    wget ${url} -q -O index.html
    esc_url=$(echo $url|sed -e "s/\//＼/g")
    sed -e "s/href=\"altrepo_eu.pub\"/href=\"${esc_url}altrepo_eu.pub\"/g" -i index.html
    sed -e "s/＼/\//g" -i index.html
    continue
  else
    url=${1}${dir:2}
    wget ${url} -q -O ${dir}/index.html
  fi
done
