#!/bin/sh
root=$HOME
cd $root
dir=.
cd $dir
wget http://debian.altrepo.eu"${dir:1}" -O index.html
cd $root
dir=./dists
cd $dir
wget http://debian.altrepo.eu"${dir:1}" -O index.html
cd $root
dir=./dists/wily
cd $dir
wget http://debian.altrepo.eu"${dir:1}" -O index.html
cd $root
dir=./dists/wily/main
cd $dir
wget http://debian.altrepo.eu"${dir:1}" -O index.html
cd $root
dir=./dists/wily/main/source
cd $dir
wget http://debian.altrepo.eu"${dir:1}" -O index.html
cd $root
dir=./dists/wily/main/binary-amd64
cd $dir
wget http://debian.altrepo.eu"${dir:1}" -O index.html
cd $root
dir=./dists/wily/main/binary-armhf
cd $dir
wget http://debian.altrepo.eu"${dir:1}" -O index.html
cd $root
dir=./dists/wily/main/binary-i386
cd $dir
wget http://debian.altrepo.eu"${dir:1}" -O index.html
cd $root
dir=./dists/sid
cd $dir
wget http://debian.altrepo.eu"${dir:1}" -O index.html
cd $root
dir=./dists/sid/main
cd $dir
wget http://debian.altrepo.eu"${dir:1}" -O index.html
cd $root
dir=./dists/sid/main/source
cd $dir
wget http://debian.altrepo.eu"${dir:1}" -O index.html
cd $root
dir=./dists/sid/main/binary-amd64
cd $dir
wget http://debian.altrepo.eu"${dir:1}" -O index.html
cd $root
dir=./dists/sid/main/binary-armhf
cd $dir
wget http://debian.altrepo.eu"${dir:1}" -O index.html
cd $root
dir=./dists/sid/main/binary-i386
cd $dir
wget http://debian.altrepo.eu"${dir:1}" -O index.html
cd $root
dir=./dists/trusty
cd $dir
wget http://debian.altrepo.eu"${dir:1}" -O index.html
cd $root
dir=./dists/trusty/main
cd $dir
wget http://debian.altrepo.eu"${dir:1}" -O index.html
cd $root
dir=./dists/trusty/main/source
cd $dir
wget http://debian.altrepo.eu"${dir:1}" -O index.html
cd $root
dir=./dists/trusty/main/binary-amd64
cd $dir
wget http://debian.altrepo.eu"${dir:1}" -O index.html
cd $root
dir=./dists/trusty/main/binary-armhf
cd $dir
wget http://debian.altrepo.eu"${dir:1}" -O index.html
cd $root
dir=./dists/trusty/main/binary-i386
cd $dir
wget http://debian.altrepo.eu"${dir:1}" -O index.html
cd $root
dir=./dists/precise
cd $dir
wget http://debian.altrepo.eu"${dir:1}" -O index.html
cd $root
dir=./dists/precise/main
cd $dir
wget http://debian.altrepo.eu"${dir:1}" -O index.html
cd $root
dir=./dists/precise/main/source
cd $dir
wget http://debian.altrepo.eu"${dir:1}" -O index.html
cd $root
dir=./dists/precise/main/binary-amd64
cd $dir
wget http://debian.altrepo.eu"${dir:1}" -O index.html
cd $root
dir=./dists/precise/main/binary-armhf
cd $dir
wget http://debian.altrepo.eu"${dir:1}" -O index.html
cd $root
dir=./dists/precise/main/binary-i386
cd $dir
wget http://debian.altrepo.eu"${dir:1}" -O index.html
cd $root
dir=./dists/stable
cd $dir
wget http://debian.altrepo.eu"${dir:1}" -O index.html
cd $root
dir=./dists/stable/main
cd $dir
wget http://debian.altrepo.eu"${dir:1}" -O index.html
cd $root
dir=./dists/stable/main/source
cd $dir
wget http://debian.altrepo.eu"${dir:1}" -O index.html
cd $root
dir=./dists/stable/main/binary-amd64
cd $dir
wget http://debian.altrepo.eu"${dir:1}" -O index.html
cd $root
dir=./dists/stable/main/binary-armhf
cd $dir
wget http://debian.altrepo.eu"${dir:1}" -O index.html
cd $root
dir=./dists/stable/main/binary-i386
cd $dir
wget http://debian.altrepo.eu"${dir:1}" -O index.html
cd $root
dir=./dists/vivid
cd $dir
wget http://debian.altrepo.eu"${dir:1}" -O index.html
cd $root
dir=./dists/vivid/main
cd $dir
wget http://debian.altrepo.eu"${dir:1}" -O index.html
cd $root
dir=./dists/vivid/main/source
cd $dir
wget http://debian.altrepo.eu"${dir:1}" -O index.html
cd $root
dir=./dists/vivid/main/binary-amd64
cd $dir
wget http://debian.altrepo.eu"${dir:1}" -O index.html
cd $root
dir=./dists/vivid/main/binary-armhf
cd $dir
wget http://debian.altrepo.eu"${dir:1}" -O index.html
cd $root
dir=./dists/vivid/main/binary-i386
cd $dir
wget http://debian.altrepo.eu"${dir:1}" -O index.html
cd $root
dir=./pool
cd $dir
wget http://debian.altrepo.eu"${dir:1}" -O index.html
cd $root
dir=./pool/main
cd $dir
wget http://debian.altrepo.eu"${dir:1}" -O index.html
cd $root
dir=./pool/main/t
cd $dir
wget http://debian.altrepo.eu"${dir:1}" -O index.html
cd $root
dir=./pool/main/t/thrift
cd $dir
wget http://debian.altrepo.eu"${dir:1}" -O index.html
cd $root
dir=./pool/main/p
cd $dir
wget http://debian.altrepo.eu"${dir:1}" -O index.html
cd $root
dir=./pool/main/p/purple-line
cd $dir
wget http://debian.altrepo.eu"${dir:1}" -O index.html
