#!/bin/bash
#installe distrubition workspace to master.
./workspace
cp -r ../precise/dists ../master/
cp -r ../precise/pool ../master/
cp -r ../sid/dists ../master/
cp -r ../sid/pool ../master/
cp -r ../stable/dists ../master/
cp -r ../stable/pool ../master/
cp -r ../trusty/dists ../master/
cp -r ../trusty/pool ../master/
cp -r ../vivid/dists ../master/
cp -r ../vivid/pool ../master/
cp -r ../wily/dists ../master/
cp -r ../wily/pool ../master/
cd ../master
git commit -a
cd ../debian.altrepo.eu
