#!/bin/bash
#installer: installe distrubition workspace to master.
#$1: program to install.
$(dirname $0)/workspace
rm -rf ../master/pool/main/${1:0:1}/$1/*.dsc ../master/pool/main/${1:0:1}/$1/*.deb ../master/pool/main/${1:0:1}/$1/*.gz ../master/pool/main/${1:0:1}/$1/*.xz
cp -r ../precise/dists ../master/
cp -r ../precise/pool ../master/
cp -r ../sid/dists ../master/
cp -r ../sid/pool ../master/
cp -r ../stable/dists ../master/
cp -r ../stable/pool ../master/
cp -r ../trusty/dists ../master/
cp -r ../trusty/pool ../master/
cp -r ../vivid/dists ../master/
cp -r ../vivid/pool ../master/
cp -r ../wily/dists ../master/
cp -r ../wily/pool ../master/
cd ../master
git add --all
git commit -a
cd ../debian.altrepo.eu
