#!/bin/bash
if [ `$(dirname $0)/countstr groups docker` != 1 ];then
 echo "Couldn't run docker.Abort.">&2
exit
fi
#import configuration.
source ../tools/conf

#Build
#precise
../tools/importer \
precise \
ubuntu \
${source_version[0]} \
"cp $PROJECT/patches/0001-patch-for-precise.patch /mnt" \
"cd purple-line&&patch -p1 < /mnt/0001-patch-for-precise.patch&&cd /" \
"rm -rf /mnt/0001-patch-for-precise.patch" \

#sid
../tools/importer \
sid \
debian \
${source_version[0]} \
"cp $PROJECT/patches/0001-change-build-dep.patch /mnt" \
"cd thrift-1.0.0&&patch -p1 < /mnt/0001-change-build-dep.patch&&cd /" \
"rm -rf /mnt/0001-change-build-dep.patch" \

#stable
../tools/importer \
stable \
debian \
${source_version[0]} \
"cp $PROJECT/patches/0001-change-build-dep.patch /mnt" \
"cd thrift-1.0.0&&patch -p1 < /mnt/0001-change-build-dep.patch&&cd /" \
"rm -rf /mnt/0001-change-build-dep.patch" \

#trusty
../tools/importer \
trusty \
ubuntu \
${source_version[0]} \
"cp $PROJECT/patches/0001-change-build-dep.patch /mnt" \
"cd thrift-1.0.0&&patch -p1 < /mnt/0001-change-build-dep.patch&&cd /" \
"rm -rf /mnt/0001-change-build-dep.patch" \

#vivid
../tools/importer \
vivid \
ubuntu \
${source_version[0]} \
"cp $PROJECT/patches/0001-change-build-dep.patch /mnt" \
"cd thrift-1.0.0&&patch -p1 < /mnt/0001-change-build-dep.patch&&cd /" \
"rm -rf /mnt/0001-change-build-dep.patch" \

#wily
../tools/importer \
wily \
ubuntu \
${source_version[0]} \
"cp $PROJECT/patches/0001-change-build-dep.patch /mnt" \
"cd thrift-1.0.0&&patch -p1 < /mnt/0001-change-build-dep.patch&&cd /" \
"rm -rf /mnt/0001-change-build-dep.patch" \


../tools/update precise
../tools/update sid
../tools/update stable
../tools/update trusty
../tools/update vivid
../tools/update wily
../tools/installer purple-line
../tools/installer thrift
../tools/pushto
