#!/bin/sh
#CodeNames
PRECISE=0000
SID=1111
STABLE=2222
TRUSTY=3333
VIVID=4444
WILY=5555
PURPLE_LINE_VERSION=0.1
THRIFT_VERSION=1.0.0-dev
git checkout $1
command=$(echo $2)
$command &&
yes n|debsign ./pool/main/*/*/*.dsc
apt-ftparchive sources .>Sources
apt-ftparchive packages .>Packages
a=$(sed -e "s/\.\/pool/pool/" Sources)
echo "$a">Sources
mv Sources ./dists/*/main/source/Sources
a=$(sed -e "s/\.\/pool/pool/" Packages)
echo "$a">Packages
mv Packages ./dists/*/main/binary-amd64/Packages
cd dists/*
rhead=$(head -8 Release)
rm -rf Release
release=$(apt-ftparchive release .)
echo "${rhead}""\n""$release">Release
gpg -b -a Release
mv Release.asc Release.gpg
cd ../../
git commit -a
