#!/bin/sh
#update: update debian repository.
#$1: code name.
#$2: command to exec.
restore=$(pwd)
cd ../$1
command=$(echo $2)
$command
yes n|debsign ./pool/main/*/*/*.dsc
apt-ftparchive sources .>Sources
apt-ftparchive packages .>Packages
a=$(sed -e "s/\.\/pool/pool/" Sources)
echo "$a">Sources
mv Sources ./dists/*/main/source/Sources
a=$(sed -e "s/\.\/pool/pool/" Packages)
echo "$a">Packages
mv Packages ./dists/*/main/binary-amd64/Packages
cd dists/*
rhead=$(head -8 Release)
rm -rf Release
release=$(apt-ftparchive release .)
printf "${rhead}\n$release\n">Release
gpg -b -a Release
mv Release.asc Release.gpg
cd ../../
git add --all
git commit -a
cd $restore
