#!/bin/bash
#workspace: Create a workspace for distribution.
git-new-workdir . ../precise precise
git-new-workdir . ../sid sid
git-new-workdir . ../stable stable
git-new-workdir . ../trusty trusty
git-new-workdir . ../vivid vivid
git-new-workdir . ../wily wily
git-new-workdir . ../master master
git-new-workdir . ../tools tools
